### ISSUE TITLE
Packages needed

### ISSUE THREAD

**Issue by elmerehbi** [sux13/DataScienceSpCourseNotes#6]
What are the packages needed for the whole repo?
I added something to the 8th course and built it but several things failed like the ToC.
If you can supply me the packages used I'll make a script that installs them all so we can add it to the repo.

Alternatively you can add them to my repo: https://github.com/elmerehbi/Ubuntu-Cusomization-Script/blob/master/r-cusomize.R

**Comment by sux13** [comment]
let me take a look

**Comment by sux13** [comment]
Here's my session info. I'm not sure which package you are missing. Let me know if this helps.

R version 3.1.3 (2015-03-09) Platform: x86_64-apple-darwin13.4.0 (64-bit) Running under: OS X 10.10.3(Yosemite)locale: [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8attached base packages: [1] stats4 splines parallel grid stats graphics grDevices [8] utils datasets methods baseother attached packages: [1] forecast_5.9 timeDate_3012.100[3] quantmod_0.4-4 TTR_0.22-0[5] xts_0.9-7 mgcv_1.8-6[7] nlme_3.1-120 lars_1.2[9] klaR_0.6-12 MASS_7.3-40[11] plyr_1.8.2 gbm_2.1.1[13] randomForest_4.6-10 party_1.0-20[15] strucchange_1.5-0 sandwich_2.3-3[17] zoo_1.7-12 modeltools_0.2-21[19] mvtnorm_1.0-2 ElemStatLearn_2012.04-0 [21] rpart_4.1-9 gridExtra_0.9.1[23] Hmisc_3.16-0 Formula_1.2-1[25] survival_2.38-1 ISLR_1.0[27] caret_6.0-41 ggplot2_1.0.1[29] lattice_0.20-31 kernlab_0.9-20[31] doMC_1.3.3 iterators_1.0.7[33] foreach_1.4.2 png_0.1-7loaded via a namespace (and not attached): [1] acepack_1.3-3.3 BradleyTerry2_1.0-6 brglm_0.5-9[4] car_2.0-25 class_7.3-12 cluster_2.0.1[7] codetools_0.2-11 coin_1.0-24 colorspace_1.2-6[10] combinat_0.0-8 compiler_3.1.3 digest_0.6.8[13] e1071_1.6-4 evaluate_0.7 foreign_0.8-63[16] formatR_1.2 fracdiff_1.4-2 gtable_0.1.2[19] gtools_3.4.2 htmltools_0.2.6 knitr_1.10[22] labeling_0.3 latticeExtra_0.6-26 lme4_1.1-7[25] Matrix_1.2-0 minqa_1.2.4 munsell_0.4.2[28] nloptr_1.0.4 nnet_7.3-9 pbkrtest_0.4-2[31] proto_0.3-10 quadprog_1.5-5 quantreg_5.11[34] RANN_2.5 rattle_3.4.1 RColorBrewer_1.1-2 [37] Rcpp_0.11.6 reshape2_1.4.1 rmarkdown_0.5.3.1[40] rpart.plot_1.5.2 scales_0.2.4 SparseM_1.6[43] stringr_0.6.2 tools_3.1.3 tseries_0.10-34[46] yaml_2.1.13

**Comment by elmerehbi** [comment]
When I tried to build I used Rscript from the terminal. Probably that's the problem.
Anyway, thanks I'll see what's missing.

**Comment by sux13** [comment]
I used Rstudio. Let me know if you still have issues.
